[build-system]
requires = [ "setuptools", "setuptools-github", "wheel" ]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88

[[tool.mypy.overrides]]
module = [
  "docutils.core",
  "markdown2"
]
ignore_missing_imports = true